# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      # The recommended scrape interval is 60s.
      timeInterval: '60s'
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
